# this entire script was generated by iterating with Bing's chatGPT feature. whoa.
import os
import random
from datetime import datetime
from ftplib import FTP

def generate_number_string(num_groups: int):
    groups = []
    for i in range(num_groups):
        for j in range(17):
            first = str(random.randint(1, 3))
            second = str(random.randint(1, 3))
            third = str(random.randint(1, 4))
            group = first + second + third
            groups.append(group)
    number_string = ''.join(groups)
    return number_string

# Example usage: generate a string with 2 groups of 17 and write it to two directories on an FTP server
num_groups = 100
number_string = generate_number_string(num_groups)

# Change local directories
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

date_str = datetime.now().strftime('%m%d%Y')
filename = f'dailyChallenge{date_str}.txt'

# Prompt for FTP username and password
ftp_username = input('Enter your FTP username: ')
ftp_password = input('Enter your FTP password: ')

# Connect to the FTP server
ftp = input('Enter your FTP server: ')
ftp.login(ftp_username, ftp_password)

# Write the generated number string to a local file
with open(filename, 'wb') as f:
    f.write(number_string.encode())

# Write to first file in "public_html/likeme/dailyChallenges" directory
output_dir1 = 'likeme/dailyChallenges'
output_path1 = os.path.join(output_dir1, filename)
ftp.cwd('likeme/dailyChallenges')
try:
    if filename in ftp.nlst():
        print(f'File already exists: {output_path1}')
    else:
        ftp.cwd('/')
        with open(filename, 'rb') as f:
            ftp.storbinary(f'STOR {output_path1}', f)
        print(f'Number string written to file: {output_path1}')
except Exception as e:
    print(f'Error writing to file: {output_path1}: {e}')

# Write to second file in "public_html/pp_likeme/dailyChallenges" directory
output_dir2 = 'pp_likeme/dailyChallenges'
output_path2 = os.path.join(output_dir2, filename)
ftp.cwd('/pp_likeme/dailyChallenges')
try:
    if filename in ftp.nlst():
        print(f'File already exists: {output_path2}')
    else:
        ftp.cwd('/')
        with open(filename, 'rb') as f:
            ftp.storbinary(f'STOR {output_path2}', f)
        print(f'Number string written to file: {output_path2}')
except Exception as e:
    print(f'Error writing to file: {output_path2}: {e}')

# Close the FTP connection
ftp.quit()