# this entire script was generated by iterating with Bing's chatGPT feature. whoa.
import os
import random
from datetime import datetime, timezone
from ftplib import FTP

number_string = str(datetime.now(timezone.utc).toordinal())

# Change local directories
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

date_str = datetime.now(timezone.utc).strftime('%m%d%Y')
filename = f'dailyChallenge{date_str}.txt'

# Prompt for FTP username and password
ftp_username = input('Enter your FTP username: ')
ftp_password = input('Enter your FTP password: ')

# Connect to the FTP server
ftp = input('Enter your FTP server: ')
ftp.login(ftp_username, ftp_password)

# Write the generated number string to a local file
with open(filename, 'wb') as f:
    f.write(number_string.encode())

# Write to first file in "public_html/likeme/dailyChallenges" directory
output_dir1 = 'likeme/dailyChallengeSeeds'
output_path1 = os.path.join(output_dir1, filename)
ftp.cwd('likeme/dailyChallengeSeeds')
try:
    if filename in ftp.nlst():
        print(f'File already exists: {output_path1}')
    else:
        ftp.cwd('/')
        with open(filename, 'rb') as f:
            ftp.storbinary(f'STOR {output_path1}', f)
        print(f'Number string written to file: {output_path1}')
except Exception as e:
    print(f'Error writing to file: {output_path1}: {e}')

# Write to second file in "public_html/pp_likeme/dailyChallenges" directory
output_dir2 = 'pp_likeme/dailyChallengeSeeds'
output_path2 = os.path.join(output_dir2, filename)
ftp.cwd('/pp_likeme/dailyChallengeSeeds')
try:
    if filename in ftp.nlst():
        print(f'File already exists: {output_path2}')
    else:
        ftp.cwd('/')
        with open(filename, 'rb') as f:
            ftp.storbinary(f'STOR {output_path2}', f)
        print(f'Number string written to file: {output_path2}')
except Exception as e:
    print(f'Error writing to file: {output_path2}: {e}')

# Close the FTP connection
ftp.quit()